### PR TITLE
fix: convert the pointer values of type uchar to unsafe.Pointer before converting them to *char

### PR DESCRIPTION
**Pull request by FelixTing**
Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Comment by FelixTing** [comment]
@vladimirvivien I found a type-casting issue and tried to fix it. But I don't know CGO in much detail. I'd appreciate it if you could help review the change. Thanks!

**Review by vladimirvivien — APPROVED** [review]
LGTM.
Thanks for submitting this!!

**Comment by vladimirvivien** [comment]
🎉  @FelixTing thank you for submitting this patch. Good catch.

**Comment by FelixTing** [comment]
@vladimirvivien Thank you for your help.

**Pull request merged**
